name: Build and Push ARM Docker Image

on:
  push:
    branches:
      - deploy_experimental

jobs:
  build_and_push_arm:
    name: Build and Push ARM Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB }}

      - name: Build and push ARM image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./setup/Dockerfile_experimental
          platforms: linux/arm/v7,linux/arm64
          push: true
          tags: |
            hannesschniz/classcompass:arm-experimental
            hannesschniz/classcompass:arm-${{ github.sha }}
